
                 /* Header file for VIF cmodes definition module */

#ifndef _VIF_init_h
#define _VIF_init_h

#include "config.h"

CF_HEADER( VIF_init_h_init, \
    "$Id: VIF_init.h,v 2.2 1995/03/29 13:05:26 ella Exp $" )

/* #define Config_VIF_init "DRA VIF_init 0.1 22-Dec-1993 16:15" */


/* 
    ************************************************************************
    This Program is the property of the Secretary of State for Defence
    (United Kingdom) acting through the Defence Research Agency (DRA). Use,
    reproduction, production of amended versions and/or transfer of this
    Program is permitted provided that:

  (a)  this legend be preserved on any such reproduction and amended version,
  (b)  any amended version of this Program be clearly marked to show the
       nature of the amendment and of the name of the amending organisation,
  and
  (c)  any recipient  of such reproduction or amended version accept the
       conditions set out in this legend.

                         Crown Copyright, (c)   1993

                             All rights reserved.

    The Secretary of State for Defence (United Kingdom) acting through his
    Defence Research Agency (DRA) gives no warranty that any element of the
    Software is suitable for any purpose and he shall not be liable for any
    loss or damage including loss or damage resulting in injury or death
    howsoever caused which results from the use of the Software, or any
    developments adaptions modifications translations and enhancements
    thereof.

    The original authors may be contacted via email on ella@dra.hmg.gb or by
    writing to ELLA Office, DRA, St Andrews Road, Malvern, Worcs WR14 3PS, UK.
    ************************************************************************

   ------------------------- Change History ---------------------------
22:12:93  Module created - initially without tests for NULL Nodes.  DCT
06:01:95   1.001  ELLA    Install in config manage system. 
29:03:95   2.002  ELLA  Change copyright header
??:??:??   ?.???  ????
*/

#include "cmodes.h"

#define VIF_SIGNATURE "V01_VIF"

#define INT 1
#define ID 2
#define VEC 3

#define VIF_NSTRUCTS 152
#define VIF_ACCESS_TYPE_DECL 20
#define VIF_ALIAS_DECL 21
#define VIF_ALLOCATED 22
#define VIF_ALLOCATOR 23
#define VIF_ARCHITECTURE_BODY 24
#define VIF_ASCENDING_RANGE_CONSTRAINT 25
#define VIF_ASSERTION_STM 26
#define VIF_ATTRIBUTE_DECL 27
#define VIF_ATTRIBUTE_SPEC 28
#define VIF_BINARY_OPERATION 29
#define VIF_BINDING_INDICATION 30
#define VIF_BIT_STRING_LITERAL 31
#define VIF_BIT_STRING_LITERAL_SUB_AGG 32
#define VIF_BLOCK_CONFIG 33
#define VIF_BLOCK_STM 34
#define VIF_CASE_ALTERNATIVE_FOR_DISCRETE 35
#define VIF_CASE_ALTERNATIVE_FOR_STRING 36
#define VIF_CASE_STM 37
#define VIF_CHAR_LITERAL_DECL 38
#define VIF_CLOSURE 39
#define VIF_COMP_INSTANTIATE_STM 40
#define VIF_COMPLETE_ASSOCIATION_OF_FORMAL 41
#define VIF_COMPONENT_CONFIG 42
#define VIF_COMPONENT_DECL 43
#define VIF_CONCURRENT_ASSERTION_STM 44
#define VIF_CONCURRENT_PROC_CALL_STM 45
#define VIF_COND_ALTERNATIVE 46
#define VIF_CONDITIONAL_SIGNAL_ASSIGN_STM 47
#define VIF_CONDITIONAL_WAVEFORM_ALT 48
#define VIF_CONFIGURATION_DECL 49
#define VIF_CONFIGURATION_SPEC 50
#define VIF_CONSTANT_DECL 51
#define VIF_CONSTRAINED_ARRAY_TYPE_DECL 52
#define VIF_CONVERSION_FUNCTION_ON_ASSOC 53
#define VIF_CONVERSION_FUNCTION_ON_PARTIAL_FORMAL 54
#define VIF_DESCENDING_RANGE_CONSTRAINT 55
#define VIF_DESIGN_LIBRARY 56
#define VIF_DESIGN_UNIT 57
#define VIF_DISCONNECTION_SPEC 58
#define VIF_ELEMENT_DECL 59
#define VIF_ENTITY_DECL 60
#define VIF_ENTITY_INSTANTIATE_STM 61
#define VIF_ENUM_LITERAL_DECL 62
#define VIF_ENUM_TYPE_DECL 63
#define VIF_EXIT_STM 64
#define VIF_FILE_DECL 65
#define VIF_FILE_TYPE_DECL 66
#define VIF_FLOATING_TYPE_DECL 67
#define VIF_FOR_GENERATION 68
#define VIF_FOR_ITERATION 69
#define VIF_FUNC_BODY 70
#define VIF_FUNC_CALL 71
#define VIF_FUNC_DECL 72
#define VIF_GATHERED_PARTIAL_ASSOCIATIONS 73
#define VIF_GENERAL_NAMED_ENTITY 74
#define VIF_GENERAL_SUBTYPE_DECL 75
#define VIF_GENERAL_USED_OBJECT 76
#define VIF_GENERATE_STM 77
#define VIF_GENERIC_PARAM_DECL 78
#define VIF_GROUP_DECL 79
#define VIF_GROUP_TEMPLATE_DECL 80
#define VIF_GROUP_TEMPLATE_ENTRY 81
#define VIF_IF_GENERATION 82
#define VIF_IF_STM 83
#define VIF_IMPLICIT_FUNC_DECL 84
#define VIF_IMPLICIT_OPERATOR_DECL 85
#define VIF_IMPLICIT_PROC_DECL 86
#define VIF_INCOMPLETE_TYPE_DECL 87
#define VIF_INDEX_CONSTRAINT 88
#define VIF_INDEXED 89
#define VIF_INDEXED_ATTRIBUTE_REF 90
#define VIF_INDEXED_FUNC_CALL 91
#define VIF_INDEXED_FUNC_DECL 92
#define VIF_INT_32_RANGE 93
#define VIF_INT_32_VALUE 94
#define VIF_INT_64_VALUE 95
#define VIF_INTEGER_TYPE_DECL 96
#define VIF_LABEL_DECL 97
#define VIF_LOOP_STM 98
#define VIF_NAMED_AGG_ASSOC 99
#define VIF_NAMED_ARRAY_AGG 100
#define VIF_NAMED_SUB_AGG 101
#define VIF_NEXT_STM 102
#define VIF_NON_CONSTRAINT 103
#define VIF_NON_STATIC_ARRAY_AGG 104
#define VIF_NON_STATIC_SUB_AGG 105
#define VIF_NULL_ARRAY_AGG 106
#define VIF_NULL_LITERAL 107
#define VIF_NULL_STM 108
#define VIF_NULL_SUB_AGG 109
#define VIF_NULL_WAVEFORM_ELEMENT 110
#define VIF_NUMERIC_VALUE 111
#define VIF_OPERATOR_DECL 112
#define VIF_OTHERS_AGG_ASSOC 113
#define VIF_OTHERS_CASE_ALTERNATIVE 114
#define VIF_OTHERS_SELECTED_WAVEFORM_ALT 115
#define VIF_PACKAGE_BODY 116
#define VIF_PACKAGE_DECL 117
#define VIF_PARTIAL_ASSOCIATION_OF_FORMAL 118
#define VIF_PHY_UNIT_DECL 119
#define VIF_PHYSICAL_TYPE_DECL 120
#define VIF_PHYSICAL_VALUE 121
#define VIF_PORT_DECL 122
#define VIF_POSITIONAL_AGG_ASSOC 123
#define VIF_POSITIONAL_ARRAY_AGG 124
#define VIF_POSITIONAL_SUB_AGG 125
#define VIF_PRE_DEFINED_ATT_DECL 126
#define VIF_PROC_BODY 127
#define VIF_PROC_CALL_STM 128
#define VIF_PROC_DECL 129
#define VIF_PROCESS_STM 130
#define VIF_QUALIFIED 131
#define VIF_RANGE_ATTRIBUTE_CONSTRAINT 132
#define VIF_REAL_VALUE 133
#define VIF_RECORD_AGG 134
#define VIF_RECORD_TYPE_DECL 135
#define VIF_REPORT_STM 136
#define VIF_RESOLVABLE_SUBTYPE_DECL 137
#define VIF_RETURN_STM 138
#define VIF_REVERSE_RANGE_ATTRIBUTE_CONSTRAINT 139
#define VIF_SELECTED_ELEMENT 140
#define VIF_SELECTED_SIGNAL_ASSIGN_STM 141
#define VIF_SELECTED_WAVEFORM_ALT_FOR_DISCRETE 142
#define VIF_SELECTED_WAVEFORM_ALT_FOR_STRING 143
#define VIF_SHARED_VARIABLE_DECL 144
#define VIF_SIGNAL_ASSIGN_STM 145
#define VIF_SIGNAL_DECL 146
#define VIF_SIGNAL_DISCONNECT_SPEC 147
#define VIF_SIGNAL_SPEC_AGG 148
#define VIF_SIGNAL_SPEC_ASSOC 149
#define VIF_SIMPLE_ATTRIBUTE_REF 150
#define VIF_SLICE 151
#define VIF_STRING_LITERAL 152
#define VIF_STRING_LITERAL_SUB_AGG 153
#define VIF_STRING_VALUE 154
#define VIF_SUBP_PARAM_DECL 155
#define VIF_SUBTYPE_INDICATOR 156
#define VIF_SYMBOL_ENTRY_IN_TABLE 157
#define VIF_TYPE_CONVERSION 158
#define VIF_TYPE_CONVERSION_ON_ASSOC 159
#define VIF_TYPE_CONVERSION_ON_PARTIAL_FORMAL 160
#define VIF_UNARY_OPERATION 161
#define VIF_UNCONNECTED 162
#define VIF_UNCONSTRAINED_ARRAY_TYPE_DECL 163
#define VIF_UNIV_INTEGER_TYPE_DECL 164
#define VIF_UNIV_REAL_TYPE_DECL 165
#define VIF_USE_CLAUSE 166
#define VIF_VARIABLE_ASSIGN_STM 167
#define VIF_VARIABLE_DECL 168
#define VIF_WAIT_STM 169
#define VIF_WAVEFORM_ELEMENT 170
#define VIF_WHILE_ITERATION 171

#define VIF_NUNIONS 46
#define VIF_ASSOCIATIONS 200
#define VIF_AGG_ASSOC 201
#define VIF_ATTRIBUTE 202
#define VIF_ATTRIBUTE_FORM_RANGE_CONSTRAINT 203
#define VIF_BOUNDED_FORM_RANGE_CONSTRAINT 204
#define VIF_CASE_ALTERNATIVE 205
#define VIF_CONCURRENT_STM 206
#define VIF_CONFIG_ITEM 207
#define VIF_ENUMERATION_LITERAL 208
#define VIF_FORMAL_PART 209
#define VIF_FUNC_DEF 210
#define VIF_GENERATION 211
#define VIF_ITERATION 212
#define VIF_LIBRARY_UNIT_ITEM 213
#define VIF_OBJECT_ITEM 214
#define VIF_OBJ_NAME 215
#define VIF_PROC_DEF 216
#define VIF_RANGE_CONSTRAINT_CLASS 217
#define VIF_REGION_PART 218
#define VIF_SCHEME 219
#define VIF_SELECTED_ALTERNATIVE 220
#define VIF_SEQUENTIAL_STM 221
#define VIF_STATEMENT 222
#define VIF_STATIC_VALUE 223
#define VIF_SUBP_BODY 224
#define VIF_SUBTYPE_DECL 225
#define VIF_SUB_AGG 226
#define VIF_SUB_ELEMENT 227
#define VIF_TARGET 228
#define VIF_TOP_LEVEL_AGG 229
#define VIF_TYPE_DECL 230
#define VIF_TYPE_MARK_DECL 231
#define VIF_USED_BLOCK 232
#define VIF_WAVEFORM_ELEM 233
#define VIF_AGGREGATE 234
#define VIF_ALTERNATIVE 235
#define VIF_CONSTRAINT 236
#define VIF_ITEM 237
#define VIF_NAME_EXP 238
#define VIF_PARTIAL_FORMAL_PART 239
#define VIF_SIGNAL_SPECS 240
#define VIF_ACTUAL_PART 241
#define VIF_CHOICE 242
#define VIF_IMPORTED_ITEM 243
#define VIF_INDEX_SPEC 244
#define VIF_NAMED_ENTITY 245

#define VIF_SECSTATIC_VALUE Sec(VIF_STATIC_VALUE)
#define VIF_SECREGION_PART Sec(VIF_REGION_PART)
#define VIF_SECVECATTRIBUTE_SPEC Sec(Vec(VIF_ATTRIBUTE_SPEC))
#define VIF_SECFUNC_DECL Sec(VIF_FUNC_DECL)
#define VIF_SECCONSTRAINT Sec(VIF_CONSTRAINT)
#define VIF_SECITEM Sec(VIF_ITEM)
#define VIF_SECENTITY_DECL Sec(VIF_ENTITY_DECL)
#define VIF_VECITEM Vec(VIF_ITEM)
#define VIF_SECOBJECT_ITEM Sec(VIF_OBJECT_ITEM)
#define VIF_SECTYPE_DECL Sec(VIF_TYPE_DECL)
#define VIF_SECTYPE_MARK_DECL Sec(VIF_TYPE_MARK_DECL)
#define VIF_SECATTRIBUTE_DECL Sec(VIF_ATTRIBUTE_DECL)
#define VIF_SECFUNC_DEF Sec(VIF_FUNC_DEF)
#define VIF_VECGENERIC_PARAM_DECL Vec(VIF_GENERIC_PARAM_DECL)
#define VIF_VECCOMPLETE_ASSOCIATION_OF_FORMAL Vec(VIF_COMPLETE_ASSOCIATION_OF_FORMAL)
#define VIF_SECARCHITECTURE_BODY Sec(VIF_ARCHITECTURE_BODY)
#define VIF_SECCONFIGURATION_DECL Sec(VIF_CONFIGURATION_DECL)
#define VIF_SECUSED_BLOCK Sec(VIF_USED_BLOCK)
#define VIF_VECUSE_CLAUSE Vec(VIF_USE_CLAUSE)
#define VIF_VECCONFIG_ITEM Vec(VIF_CONFIG_ITEM)
#define VIF_VECPORT_DECL Vec(VIF_PORT_DECL)
#define VIF_SECCASE_ALTERNATIVE Sec(VIF_CASE_ALTERNATIVE)
#define VIF_VECALTERNATIVE Vec(VIF_ALTERNATIVE)
#define VIF_VECDESIGN_UNIT Vec(VIF_DESIGN_UNIT)
#define VIF_SECCONFIGURATION_SPEC Sec(VIF_CONFIGURATION_SPEC)
#define VIF_SECCOMPONENT_DECL Sec(VIF_COMPONENT_DECL)
#define VIF_SECVECCOMP_INSTANTIATE_STM Sec(Vec(VIF_COMP_INSTANTIATE_STM))
#define VIF_VECCONDITIONAL_WAVEFORM_ALT Vec(VIF_CONDITIONAL_WAVEFORM_ALT)
#define VIF_VECWAVEFORM_ELEM Vec(VIF_WAVEFORM_ELEM)
#define VIF_SECCONSTANT_DECL Sec(VIF_CONSTANT_DECL)
#define VIF_VECDESIGN_LIBRARY Vec(VIF_DESIGN_LIBRARY)
#define VIF_SECVECUSE_CLAUSE Sec(Vec(VIF_USE_CLAUSE))
#define VIF_SECVECITEM Sec(Vec(VIF_ITEM))
#define VIF_VECENUMERATION_LITERAL Vec(VIF_ENUMERATION_LITERAL)
#define VIF_SECLOOP_STM Sec(VIF_LOOP_STM)
#define VIF_SECIMPORTED_ITEM Sec(VIF_IMPORTED_ITEM)
#define VIF_VECASSOCIATIONS Vec(VIF_ASSOCIATIONS)
#define VIF_VECSUBP_PARAM_DECL Vec(VIF_SUBP_PARAM_DECL)
#define VIF_SECSUBP_BODY Sec(VIF_SUBP_BODY)
#define VIF_VECPARTIAL_ASSOCIATION_OF_FORMAL Vec(VIF_PARTIAL_ASSOCIATION_OF_FORMAL)
#define VIF_SECGROUP_TEMPLATE_DECL Sec(VIF_GROUP_TEMPLATE_DECL)
#define VIF_VECNAMED_ENTITY Vec(VIF_NAMED_ENTITY)
#define VIF_VECGROUP_TEMPLATE_ENTRY Vec(VIF_GROUP_TEMPLATE_ENTRY)
#define VIF_VECSUBTYPE_INDICATOR Vec(VIF_SUBTYPE_INDICATOR)
#define VIF_VECNAME_EXP Vec(VIF_NAME_EXP)
#define VIF_SECATTRIBUTE Sec(VIF_ATTRIBUTE)
#define VIF_SECLABEL_DECL Sec(VIF_LABEL_DECL)
#define VIF_SECVECCONSTANT_DECL Sec(Vec(VIF_CONSTANT_DECL))
#define VIF_SECVECTYPE_MARK_DECL Sec(Vec(VIF_TYPE_MARK_DECL))
#define VIF_VECPHY_UNIT_DECL Vec(VIF_PHY_UNIT_DECL)
#define VIF_SECPHY_UNIT_DECL Sec(VIF_PHY_UNIT_DECL)
#define VIF_SECPROC_DEF Sec(VIF_PROC_DEF)
#define VIF_SECNAME_EXP Sec(VIF_NAME_EXP)
#define VIF_VECELEMENT_DECL Vec(VIF_ELEMENT_DECL)
#define VIF_SECELEMENT_DECL Sec(VIF_ELEMENT_DECL)
#define VIF_VECSELECTED_ALTERNATIVE Vec(VIF_SELECTED_ALTERNATIVE)
#define VIF_SECSELECTED_ALTERNATIVE Sec(VIF_SELECTED_ALTERNATIVE)
#define VIF_SECDISCONNECTION_SPEC Sec(VIF_DISCONNECTION_SPEC)
#define VIF_VECSIGNAL_SPEC_ASSOC Vec(VIF_SIGNAL_SPEC_ASSOC)
#define VIF_SECSUBTYPE_INDICATOR Sec(VIF_SUBTYPE_INDICATOR)
#define VIF_SECSUBP_PARAM_DECL Sec(VIF_SUBP_PARAM_DECL)
#define VIF_SECSYMBOL_ENTRY_IN_TABLE Sec(VIF_SYMBOL_ENTRY_IN_TABLE)
#define VIF_SECVECSYMBOL_ENTRY_IN_TABLE Sec(Vec(VIF_SYMBOL_ENTRY_IN_TABLE))
#define VIF_SECDESIGN_LIBRARY Sec(VIF_DESIGN_LIBRARY)

#define Access_type_declHas_evaluation_time(x) Index(Children(x),1)
#define Access_type_declHas_constraint(x) Index(Children(x),2)
#define Access_type_declHas_id(x) Index(Children(x),3)
#define Access_type_declHas_value_type(x) Index(Children(x),4)
#define Access_type_declHas_enclosing_scope(x) Index(Children(x),5)
#define Access_type_declHas_srcpos(x) Index(Children(x),6)
#define Access_type_declHas_value_constraint(x) Index(Children(x),7)
#define Access_type_declHas_user_att_s(x) Index(Children(x),8)
#define Alias_declHas_evaluation_time(x) Index(Children(x),1)
#define Alias_declHas_constraint(x) Index(Children(x),2)
#define Alias_declHas_id(x) Index(Children(x),3)
#define Alias_declHas_aliased_object(x) Index(Children(x),4)
#define Alias_declHas_value(x) Index(Children(x),5)
#define Alias_declHas_enclosing_scope(x) Index(Children(x),6)
#define Alias_declHas_srcpos(x) Index(Children(x),7)
#define Alias_declHas_resolution(x) Index(Children(x),8)
#define AllocatedHas_evaluation_time(x) Index(Children(x),1)
#define AllocatedHas_constraint(x) Index(Children(x),2)
#define AllocatedHas_prefix(x) Index(Children(x),3)
#define AllocatedHas_base_obj_def(x) Index(Children(x),4)
#define AllocatedHas_srcpos(x) Index(Children(x),5)
#define AllocatorHas_evaluation_time(x) Index(Children(x),1)
#define AllocatorHas_constraint(x) Index(Children(x),2)
#define AllocatorHas_value_constraint(x) Index(Children(x),3)
#define AllocatorHas_init_val(x) Index(Children(x),4)
#define AllocatorHas_srcpos(x) Index(Children(x),5)
#define Architecture_bodyHas_srcpos(x) Index(Children(x),1)
#define Architecture_bodyHas_entity_name(x) Index(Children(x),2)
#define Architecture_bodyHas_id(x) Index(Children(x),3)
#define Architecture_bodyHas_end_srcpos(x) Index(Children(x),4)
#define Architecture_bodyHas_decl_s(x) Index(Children(x),5)
#define Architecture_bodyHas_implicit_decl_s(x) Index(Children(x),6)
#define Architecture_bodyHas_enclosing_scope(x) Index(Children(x),7)
#define Architecture_bodyHas_guard(x) Index(Children(x),8)
#define Architecture_bodyHas_stm_s(x) Index(Children(x),9)
#define Architecture_bodyHas_user_att_s(x) Index(Children(x),10)
#define Ascending_range_constraintHas_evaluation_time(x) Index(Children(x),1)
#define Ascending_range_constraintHas_direction(x) Index(Children(x),2)
#define Ascending_range_constraintIs_type(x) Index(Children(x),3)
#define Ascending_range_constraintIs_subtype(x) Index(Children(x),4)
#define Ascending_range_constraintIn_enclosing_decl(x) Index(Children(x),5)
#define Ascending_range_constraintHas_null_range_indicator(x) Index(Children(x),6)
#define Ascending_range_constraintHas_left_bound(x) Index(Children(x),7)
#define Ascending_range_constraintHas_right_bound(x) Index(Children(x),8)
#define Assertion_stmHas_srcpos(x) Index(Children(x),1)
#define Assertion_stmHas_report_exp(x) Index(Children(x),2)
#define Assertion_stmHas_severity_exp(x) Index(Children(x),3)
#define Assertion_stmHas_assert_exp(x) Index(Children(x),4)
#define Assertion_stmHas_label(x) Index(Children(x),5)
#define Assertion_stmHas_enclosing_scope(x) Index(Children(x),6)
#define Attribute_declHas_evaluation_time(x) Index(Children(x),1)
#define Attribute_declHas_constraint(x) Index(Children(x),2)
#define Attribute_declHas_id(x) Index(Children(x),3)
#define Attribute_declHas_enclosing_scope(x) Index(Children(x),4)
#define Attribute_declHas_srcpos(x) Index(Children(x),5)
#define Attribute_specHas_srcpos(x) Index(Children(x),1)
#define Attribute_specHas_attribute_def(x) Index(Children(x),2)
#define Attribute_specHas_value_exp(x) Index(Children(x),3)
#define Binary_operationHas_evaluation_time(x) Index(Children(x),1)
#define Binary_operationHas_constraint(x) Index(Children(x),2)
#define Binary_operationHas_srcpos(x) Index(Children(x),3)
#define Binary_operationHas_left_exp(x) Index(Children(x),4)
#define Binary_operationHas_right_exp(x) Index(Children(x),5)
#define Binary_operationHas_value(x) Index(Children(x),6)
#define Binary_operationHas_func_name(x) Index(Children(x),7)
#define Binding_indicationHas_generic_assoc_s(x) Index(Children(x),1)
#define Binding_indicationHas_port_assoc_s(x) Index(Children(x),2)
#define Binding_indicationHas_bound_body_name(x) Index(Children(x),3)
#define Binding_indicationHas_bound_body(x) Index(Children(x),4)
#define Binding_indicationHas_bound_config(x) Index(Children(x),5)
#define Binding_indicationHas_bound_entity(x) Index(Children(x),6)
#define Bit_string_literalHas_evaluation_time(x) Index(Children(x),1)
#define Bit_string_literalHas_constraint(x) Index(Children(x),2)
#define Bit_string_literalHas_dimension(x) Index(Children(x),3)
#define Bit_string_literalHas_srcpos(x) Index(Children(x),4)
#define Bit_string_literalHas_value(x) Index(Children(x),5)
#define Bit_string_literal_sub_aggHas_evaluation_time(x) Index(Children(x),1)
#define Bit_string_literal_sub_aggHas_dimension(x) Index(Children(x),2)
#define Bit_string_literal_sub_aggHas_srcpos(x) Index(Children(x),3)
#define Bit_string_literal_sub_aggHas_value(x) Index(Children(x),4)
#define Block_configHas_srcpos(x) Index(Children(x),1)
#define Block_configHas_enclosing_scope(x) Index(Children(x),2)
#define Block_configHas_block(x) Index(Children(x),3)
#define Block_configHas_end_srcpos(x) Index(Children(x),4)
#define Block_configHas_imported_name_s(x) Index(Children(x),5)
#define Block_configHas_index_spec(x) Index(Children(x),6)
#define Block_configHas_next_level_s(x) Index(Children(x),7)
#define Block_stmHas_srcpos(x) Index(Children(x),1)
#define Block_stmHas_decl_s(x) Index(Children(x),2)
#define Block_stmHas_implicit_decl_s(x) Index(Children(x),3)
#define Block_stmHas_end_srcpos(x) Index(Children(x),4)
#define Block_stmHas_generic_assoc_s(x) Index(Children(x),5)
#define Block_stmHas_generic_s(x) Index(Children(x),6)
#define Block_stmHas_guard(x) Index(Children(x),7)
#define Block_stmHas_guard_exp(x) Index(Children(x),8)
#define Block_stmHas_label(x) Index(Children(x),9)
#define Block_stmHas_port_assoc_s(x) Index(Children(x),10)
#define Block_stmHas_port_s(x) Index(Children(x),11)
#define Block_stmHas_stm_s(x) Index(Children(x),12)
#define Block_stmHas_enclosing_scope(x) Index(Children(x),13)
#define Case_alternative_for_discreteIs_associated_up_to(x) Index(Children(x),1)
#define Case_alternative_for_discreteHas_stm_s(x) Index(Children(x),2)
#define Case_alternative_for_discreteHas_same_stm(x) Index(Children(x),3)
#define Case_alternative_for_stringIs_associated_to_str(x) Index(Children(x),1)
#define Case_alternative_for_stringHas_stm_s(x) Index(Children(x),2)
#define Case_alternative_for_stringHas_same_stm(x) Index(Children(x),3)
#define Case_stmHas_srcpos(x) Index(Children(x),1)
#define Case_stmHas_alternative_s(x) Index(Children(x),2)
#define Case_stmHas_case_exp(x) Index(Children(x),3)
#define Case_stmHas_end_srcpos(x) Index(Children(x),4)
#define Case_stmHas_label(x) Index(Children(x),5)
#define Case_stmHas_enclosing_scope(x) Index(Children(x),6)
#define Char_literal_declHas_evaluation_time(x) Index(Children(x),1)
#define Char_literal_declHas_constraint(x) Index(Children(x),2)
#define Char_literal_declHas_id(x) Index(Children(x),3)
#define Char_literal_declHas_enclosing_scope(x) Index(Children(x),4)
#define Char_literal_declHas_srcpos(x) Index(Children(x),5)
#define Char_literal_declHas_value(x) Index(Children(x),6)
#define Char_literal_declHas_user_att_s(x) Index(Children(x),7)
#define ClosureHas_design_unit_s(x) Index(Children(x),1)
#define Comp_instantiate_stmHas_srcpos(x) Index(Children(x),1)
#define Comp_instantiate_stmHas_config_spec(x) Index(Children(x),2)
#define Comp_instantiate_stmHas_component(x) Index(Children(x),3)
#define Comp_instantiate_stmHas_generic_assoc_s(x) Index(Children(x),4)
#define Comp_instantiate_stmHas_label(x) Index(Children(x),5)
#define Comp_instantiate_stmHas_port_assoc_s(x) Index(Children(x),6)
#define Comp_instantiate_stmHas_enclosing_scope(x) Index(Children(x),7)
#define Complete_association_of_formalHas_actual(x) Index(Children(x),1)
#define Complete_association_of_formalHas_formal(x) Index(Children(x),2)
#define Component_configHas_srcpos(x) Index(Children(x),1)
#define Component_configHas_binding(x) Index(Children(x),2)
#define Component_configHas_configured_ci_s(x) Index(Children(x),3)
#define Component_configHas_next_level(x) Index(Children(x),4)
#define Component_declHas_srcpos(x) Index(Children(x),1)
#define Component_declHas_enclosing_scope(x) Index(Children(x),2)
#define Component_declHas_id(x) Index(Children(x),3)
#define Component_declHas_end_srcpos(x) Index(Children(x),4)
#define Component_declHas_generic_s(x) Index(Children(x),5)
#define Component_declHas_port_s(x) Index(Children(x),6)
#define Component_declHas_user_att_s(x) Index(Children(x),7)
#define Concurrent_assertion_stmHas_srcpos(x) Index(Children(x),1)
#define Concurrent_assertion_stmHas_assertion_stm(x) Index(Children(x),2)
#define Concurrent_assertion_stmHas_label(x) Index(Children(x),3)
#define Concurrent_assertion_stmHas_postponed(x) Index(Children(x),4)
#define Concurrent_assertion_stmHas_enclosing_scope(x) Index(Children(x),5)
#define Concurrent_proc_call_stmHas_srcpos(x) Index(Children(x),1)
#define Concurrent_proc_call_stmHas_proc_call_stm(x) Index(Children(x),2)
#define Concurrent_proc_call_stmHas_label(x) Index(Children(x),3)
#define Concurrent_proc_call_stmHas_postponed(x) Index(Children(x),4)
#define Concurrent_proc_call_stmHas_enclosing_scope(x) Index(Children(x),5)
#define Cond_alternativeHas_condition(x) Index(Children(x),1)
#define Cond_alternativeHas_stm_s(x) Index(Children(x),2)
#define Conditional_signal_assign_stmHas_srcpos(x) Index(Children(x),1)
#define Conditional_signal_assign_stmHas_signal_name(x) Index(Children(x),2)
#define Conditional_signal_assign_stmHas_transport(x) Index(Children(x),3)
#define Conditional_signal_assign_stmHas_guard(x) Index(Children(x),4)
#define Conditional_signal_assign_stmHas_conditional_waveform_s(x) Index(Children(x),5)
#define Conditional_signal_assign_stmHas_label(x) Index(Children(x),6)
#define Conditional_signal_assign_stmHas_postponed(x) Index(Children(x),7)
#define Conditional_signal_assign_stmHas_reject_time(x) Index(Children(x),8)
#define Conditional_signal_assign_stmHas_enclosing_scope(x) Index(Children(x),9)
#define Conditional_waveform_altHas_srcpos(x) Index(Children(x),1)
#define Conditional_waveform_altHas_condition(x) Index(Children(x),2)
#define Conditional_waveform_altHas_waveform_s(x) Index(Children(x),3)
#define Configuration_declHas_srcpos(x) Index(Children(x),1)
#define Configuration_declHas_entity_name(x) Index(Children(x),2)
#define Configuration_declHas_id(x) Index(Children(x),3)
#define Configuration_declHas_end_srcpos(x) Index(Children(x),4)
#define Configuration_declHas_config(x) Index(Children(x),5)
#define Configuration_declHas_decl_s(x) Index(Children(x),6)
#define Configuration_declHas_implicit_decl_s(x) Index(Children(x),7)
#define Configuration_declHas_enclosing_scope(x) Index(Children(x),8)
#define Configuration_declHas_user_att_s(x) Index(Children(x),9)
#define Configuration_specHas_srcpos(x) Index(Children(x),1)
#define Configuration_specHas_binding(x) Index(Children(x),2)
#define Configuration_specHas_configured_ci_s(x) Index(Children(x),3)
#define Constant_declHas_evaluation_time(x) Index(Children(x),1)
#define Constant_declHas_constraint(x) Index(Children(x),2)
#define Constant_declHas_id(x) Index(Children(x),3)
#define Constant_declHas_enclosing_scope(x) Index(Children(x),4)
#define Constant_declHas_srcpos(x) Index(Children(x),5)
#define Constant_declHas_user_att_s(x) Index(Children(x),6)
#define Constant_declHas_value_exp(x) Index(Children(x),7)
#define Constant_declHas_value(x) Index(Children(x),8)
#define Constant_declHas_deferred_decl(x) Index(Children(x),9)
#define Constrained_array_type_declHas_evaluation_time(x) Index(Children(x),1)
#define Constrained_array_type_declHas_constraint(x) Index(Children(x),2)
#define Constrained_array_type_declHas_id(x) Index(Children(x),3)
#define Constrained_array_type_declHas_dimension(x) Index(Children(x),4)
#define Constrained_array_type_declHas_elem_subtype(x) Index(Children(x),5)
#define Constrained_array_type_declHas_enclosing_scope(x) Index(Children(x),6)
#define Constrained_array_type_declHas_srcpos(x) Index(Children(x),7)
#define Constrained_array_type_declHas_access_subelement(x) Index(Children(x),8)
#define Constrained_array_type_declHas_user_att_s(x) Index(Children(x),9)
#define Conversion_function_on_assocHas_convert_func_name(x) Index(Children(x),1)
#define Conversion_function_on_assocHas_constraint(x) Index(Children(x),2)
#define Conversion_function_on_assocHas_converted_exp(x) Index(Children(x),3)
#define Conversion_function_on_partial_formalHas_convert_func_name(x) Index(Children(x),1)
#define Conversion_function_on_partial_formalHas_constraint(x) Index(Children(x),2)
#define Conversion_function_on_partial_formalHas_converted_subelement(x) Index(Children(x),3)
#define Descending_range_constraintHas_evaluation_time(x) Index(Children(x),1)
#define Descending_range_constraintHas_direction(x) Index(Children(x),2)
#define Descending_range_constraintIs_type(x) Index(Children(x),3)
#define Descending_range_constraintIs_subtype(x) Index(Children(x),4)
#define Descending_range_constraintIn_enclosing_decl(x) Index(Children(x),5)
#define Descending_range_constraintHas_null_range_indicator(x) Index(Children(x),6)
#define Descending_range_constraintHas_left_bound(x) Index(Children(x),7)
#define Descending_range_constraintHas_right_bound(x) Index(Children(x),8)
#define Design_libraryHas_srcpos(x) Index(Children(x),1)
#define Design_libraryHas_enclosing_scope(x) Index(Children(x),2)
#define Design_libraryHas_id(x) Index(Children(x),3)
#define Design_unitHas_srcpos(x) Index(Children(x),1)
#define Design_unitHas_import_s(x) Index(Children(x),2)
#define Design_unitHas_referenced_lib_s(x) Index(Children(x),3)
#define Design_unitHas_unit(x) Index(Children(x),4)
#define Design_unitHas_vhdl_kind(x) Index(Children(x),5)
#define Disconnection_specHas_srcpos(x) Index(Children(x),1)
#define Disconnection_specHas_value_exp(x) Index(Children(x),2)
#define Element_declHas_evaluation_time(x) Index(Children(x),1)
#define Element_declHas_constraint(x) Index(Children(x),2)
#define Element_declHas_id(x) Index(Children(x),3)
#define Element_declHas_enclosing_scope(x) Index(Children(x),4)
#define Element_declHas_srcpos(x) Index(Children(x),5)
#define Element_declHas_resolution(x) Index(Children(x),6)
#define Element_declHas_int_32(x) Index(Children(x),7)
#define Entity_declHas_srcpos(x) Index(Children(x),1)
#define Entity_declHas_enclosing_scope(x) Index(Children(x),2)
#define Entity_declHas_id(x) Index(Children(x),3)
#define Entity_declHas_end_srcpos(x) Index(Children(x),4)
#define Entity_declHas_decl_s(x) Index(Children(x),5)
#define Entity_declHas_implicit_decl_s(x) Index(Children(x),6)
#define Entity_declHas_generic_s(x) Index(Children(x),7)
#define Entity_declHas_port_s(x) Index(Children(x),8)
#define Entity_declHas_stm_s(x) Index(Children(x),9)
#define Entity_declHas_use_clause_s(x) Index(Children(x),10)
#define Entity_declHas_subprogram_decl_s(x) Index(Children(x),11)
#define Entity_declHas_user_att_s(x) Index(Children(x),12)
#define Entity_instantiate_stmHas_srcpos(x) Index(Children(x),1)
#define Entity_instantiate_stmHas_label(x) Index(Children(x),2)
#define Entity_instantiate_stmHas_bound_body_name(x) Index(Children(x),3)
#define Entity_instantiate_stmHas_bound_body(x) Index(Children(x),4)
#define Entity_instantiate_stmHas_bound_config(x) Index(Children(x),5)
#define Entity_instantiate_stmHas_bound_entity(x) Index(Children(x),6)
#define Entity_instantiate_stmHas_generic_assoc_s(x) Index(Children(x),7)
#define Entity_instantiate_stmHas_port_assoc_s(x) Index(Children(x),8)
#define Entity_instantiate_stmHas_enclosing_scope(x) Index(Children(x),9)
#define Enum_literal_declHas_evaluation_time(x) Index(Children(x),1)
#define Enum_literal_declHas_constraint(x) Index(Children(x),2)
#define Enum_literal_declHas_id(x) Index(Children(x),3)
#define Enum_literal_declHas_enclosing_scope(x) Index(Children(x),4)
#define Enum_literal_declHas_srcpos(x) Index(Children(x),5)
#define Enum_literal_declHas_value(x) Index(Children(x),6)
#define Enum_literal_declHas_user_att_s(x) Index(Children(x),7)
#define Enum_type_declHas_evaluation_time(x) Index(Children(x),1)
#define Enum_type_declHas_constraint(x) Index(Children(x),2)
#define Enum_type_declHas_id(x) Index(Children(x),3)
#define Enum_type_declHas_enclosing_scope(x) Index(Children(x),4)
#define Enum_type_declHas_enumeral_s(x) Index(Children(x),5)
#define Enum_type_declHas_srcpos(x) Index(Children(x),6)
#define Enum_type_declIs_char_type(x) Index(Children(x),7)
#define Enum_type_declHas_user_att_s(x) Index(Children(x),8)
#define Exit_stmHas_srcpos(x) Index(Children(x),1)
#define Exit_stmHas_condition(x) Index(Children(x),2)
#define Exit_stmHas_loop_stm(x) Index(Children(x),3)
#define Exit_stmHas_label(x) Index(Children(x),4)
#define Exit_stmHas_enclosing_scope(x) Index(Children(x),5)
#define File_declHas_evaluation_time(x) Index(Children(x),1)
#define File_declHas_constraint(x) Index(Children(x),2)
#define File_declHas_id(x) Index(Children(x),3)
#define File_declHas_enclosing_scope(x) Index(Children(x),4)
#define File_declHas_srcpos(x) Index(Children(x),5)
#define File_declHas_logical_name(x) Index(Children(x),6)
#define File_declHas_mode(x) Index(Children(x),7)
#define File_declHas_user_att_s(x) Index(Children(x),8)
#define File_declHas_file_mode(x) Index(Children(x),9)
#define File_type_declHas_evaluation_time(x) Index(Children(x),1)
#define File_type_declHas_constraint(x) Index(Children(x),2)
#define File_type_declHas_id(x) Index(Children(x),3)
#define File_type_declHas_enclosing_scope(x) Index(Children(x),4)
#define File_type_declHas_srcpos(x) Index(Children(x),5)
#define File_type_declHas_user_att_s(x) Index(Children(x),6)
#define File_type_declHas_value_type(x) Index(Children(x),7)
#define File_type_declHas_value_constraint(x) Index(Children(x),8)
#define Floating_type_declHas_evaluation_time(x) Index(Children(x),1)
#define Floating_type_declHas_constraint(x) Index(Children(x),2)
#define Floating_type_declHas_id(x) Index(Children(x),3)
#define Floating_type_declHas_enclosing_scope(x) Index(Children(x),4)
#define Floating_type_declHas_srcpos(x) Index(Children(x),5)
#define Floating_type_declHas_user_att_s(x) Index(Children(x),6)
#define For_generationHas_evaluation_time(x) Index(Children(x),1)
#define For_generationHas_constraint(x) Index(Children(x),2)
#define For_generationHas_id(x) Index(Children(x),3)
#define For_generationHas_enclosing_scope(x) Index(Children(x),4)
#define For_generationHas_srcpos(x) Index(Children(x),5)
#define For_iterationHas_evaluation_time(x) Index(Children(x),1)
#define For_iterationHas_constraint(x) Index(Children(x),2)
#define For_iterationHas_id(x) Index(Children(x),3)
#define For_iterationHas_enclosing_scope(x) Index(Children(x),4)
#define For_iterationHas_srcpos(x) Index(Children(x),5)
#define Func_bodyHas_srcpos(x) Index(Children(x),1)
#define Func_bodyHas_decl_s(x) Index(Children(x),2)
#define Func_bodyHas_implicit_decl_s(x) Index(Children(x),3)
#define Func_bodyHas_end_srcpos(x) Index(Children(x),4)
#define Func_bodyHas_enclosing_scope(x) Index(Children(x),5)
#define Func_bodyHas_name(x) Index(Children(x),6)
#define Func_bodyHas_stm_s(x) Index(Children(x),7)
#define Func_callHas_evaluation_time(x) Index(Children(x),1)
#define Func_callHas_constraint(x) Index(Children(x),2)
#define Func_callHas_assoc_s(x) Index(Children(x),3)
#define Func_callHas_srcpos(x) Index(Children(x),4)
#define Func_callHas_func_name(x) Index(Children(x),5)
#define Func_callHas_value(x) Index(Children(x),6)
#define Func_declHas_evaluation_time(x) Index(Children(x),1)
#define Func_declHas_constraint(x) Index(Children(x),2)
#define Func_declHas_id(x) Index(Children(x),3)
#define Func_declHas_enclosing_scope(x) Index(Children(x),4)
#define Func_declHas_srcpos(x) Index(Children(x),5)
#define Func_declHas_param_s(x) Index(Children(x),6)
#define Func_declHas_body_decl(x) Index(Children(x),7)
#define Func_declHas_user_att_s(x) Index(Children(x),8)
#define Func_declHas_pureness(x) Index(Children(x),9)
#define Gathered_partial_associationsHas_dimension(x) Index(Children(x),1)
#define Gathered_partial_associationsHas_constraint(x) Index(Children(x),2)
#define Gathered_partial_associationsHas_gathered_assoc_s(x) Index(Children(x),3)
#define Gathered_partial_associationsHas_high_bound(x) Index(Children(x),4)
#define Gathered_partial_associationsHas_low_bound(x) Index(Children(x),5)
#define General_named_entityHas_srcpos(x) Index(Children(x),1)
#define General_named_entityHas_named_entity_def(x) Index(Children(x),2)
#define General_subtype_declHas_evaluation_time(x) Index(Children(x),1)
#define General_subtype_declHas_constraint(x) Index(Children(x),2)
#define General_subtype_declHas_id(x) Index(Children(x),3)
#define General_subtype_declHas_enclosing_scope(x) Index(Children(x),4)
#define General_subtype_declHas_srcpos(x) Index(Children(x),5)
#define General_subtype_declHas_user_att_s(x) Index(Children(x),6)
#define General_used_objectHas_evaluation_time(x) Index(Children(x),1)
#define General_used_objectHas_constraint(x) Index(Children(x),2)
#define General_used_objectHas_obj_def(x) Index(Children(x),3)
#define General_used_objectHas_srcpos(x) Index(Children(x),4)
#define General_used_objectHas_value(x) Index(Children(x),5)
#define Generate_stmHas_srcpos(x) Index(Children(x),1)
#define Generate_stmHas_decl_s(x) Index(Children(x),2)
#define Generate_stmHas_implicit_decl_s(x) Index(Children(x),3)
#define Generate_stmHas_end_srcpos(x) Index(Children(x),4)
#define Generate_stmHas_label(x) Index(Children(x),5)
#define Generate_stmHas_scheme(x) Index(Children(x),6)
#define Generate_stmHas_guard(x) Index(Children(x),7)
#define Generate_stmHas_stm_s(x) Index(Children(x),8)
#define Generate_stmHas_enclosing_scope(x) Index(Children(x),9)
#define Generic_param_declHas_evaluation_time(x) Index(Children(x),1)
#define Generic_param_declHas_constraint(x) Index(Children(x),2)
#define Generic_param_declHas_id(x) Index(Children(x),3)
#define Generic_param_declHas_class(x) Index(Children(x),4)
#define Generic_param_declHas_default(x) Index(Children(x),5)
#define Generic_param_declHas_enclosing_scope(x) Index(Children(x),6)
#define Generic_param_declHas_srcpos(x) Index(Children(x),7)
#define Generic_param_declHas_mode(x) Index(Children(x),8)
#define Generic_param_declHas_user_att_s(x) Index(Children(x),9)
#define Group_declHas_srcpos(x) Index(Children(x),1)
#define Group_declHas_enclosing_scope(x) Index(Children(x),2)
#define Group_declHas_id(x) Index(Children(x),3)
#define Group_declHas_group_template(x) Index(Children(x),4)
#define Group_declHas_constituent_s(x) Index(Children(x),5)
#define Group_declHas_user_att_s(x) Index(Children(x),6)
#define Group_template_declHas_srcpos(x) Index(Children(x),1)
#define Group_template_declHas_enclosing_scope(x) Index(Children(x),2)
#define Group_template_declHas_id(x) Index(Children(x),3)
#define Group_template_declHas_group_template_entry_s(x) Index(Children(x),4)
#define Group_template_declHas_repeat_last_entry(x) Index(Children(x),5)
#define Group_template_entryHas_entity_class(x) Index(Children(x),1)
#define If_generationHas_condition(x) Index(Children(x),1)
#define If_stmHas_srcpos(x) Index(Children(x),1)
#define If_stmHas_alternative_s(x) Index(Children(x),2)
#define If_stmHas_label(x) Index(Children(x),3)
#define If_stmHas_end_srcpos(x) Index(Children(x),4)
#define If_stmHas_enclosing_scope(x) Index(Children(x),5)
#define Implicit_func_declHas_evaluation_time(x) Index(Children(x),1)
#define Implicit_func_declHas_constraint(x) Index(Children(x),2)
#define Implicit_func_declHas_id(x) Index(Children(x),3)
#define Implicit_func_declHas_enclosing_scope(x) Index(Children(x),4)
#define Implicit_func_declHas_param_s(x) Index(Children(x),5)
#define Implicit_func_declHas_user_att_s(x) Index(Children(x),6)
#define Implicit_func_declHas_pureness(x) Index(Children(x),7)
#define Implicit_operator_declHas_evaluation_time(x) Index(Children(x),1)
#define Implicit_operator_declHas_constraint(x) Index(Children(x),2)
#define Implicit_operator_declHas_id(x) Index(Children(x),3)
#define Implicit_operator_declHas_enclosing_scope(x) Index(Children(x),4)
#define Implicit_operator_declHas_operator(x) Index(Children(x),5)
#define Implicit_operator_declHas_param_s(x) Index(Children(x),6)
#define Implicit_operator_declHas_user_att_s(x) Index(Children(x),7)
#define Implicit_operator_declHas_pureness(x) Index(Children(x),8)
#define Implicit_proc_declHas_evaluation_time(x) Index(Children(x),1)
#define Implicit_proc_declHas_enclosing_scope(x) Index(Children(x),2)
#define Implicit_proc_declHas_id(x) Index(Children(x),3)
#define Implicit_proc_declHas_param_s(x) Index(Children(x),4)
#define Implicit_proc_declHas_user_att_s(x) Index(Children(x),5)
#define Incomplete_type_declHas_srcpos(x) Index(Children(x),1)
#define Incomplete_type_declHas_enclosing_scope(x) Index(Children(x),2)
#define Incomplete_type_declHas_id(x) Index(Children(x),3)
#define Index_constraintHas_evaluation_time(x) Index(Children(x),1)
#define Index_constraintHas_index_range_s(x) Index(Children(x),2)
#define Index_constraintIs_type(x) Index(Children(x),3)
#define Index_constraintIs_subtype(x) Index(Children(x),4)
#define Index_constraintIn_enclosing_decl(x) Index(Children(x),5)
#define IndexedHas_evaluation_time(x) Index(Children(x),1)
#define IndexedHas_constraint(x) Index(Children(x),2)
#define IndexedHas_base_obj_def(x) Index(Children(x),3)
#define IndexedHas_srcpos(x) Index(Children(x),4)
#define IndexedHas_index_exp_s(x) Index(Children(x),5)
#define IndexedHas_prefix(x) Index(Children(x),6)
#define Indexed_attribute_refHas_evaluation_time(x) Index(Children(x),1)
#define Indexed_attribute_refHas_constraint(x) Index(Children(x),2)
#define Indexed_attribute_refHas_attribute(x) Index(Children(x),3)
#define Indexed_attribute_refHas_srcpos(x) Index(Children(x),4)
#define Indexed_attribute_refHas_index(x) Index(Children(x),5)
#define Indexed_attribute_refHas_attribute_prefix(x) Index(Children(x),6)
#define Indexed_attribute_refHas_value(x) Index(Children(x),7)
#define Indexed_func_callHas_srcpos(x) Index(Children(x),1)
#define Indexed_func_callHas_constraint(x) Index(Children(x),2)
#define Indexed_func_callHas_index_exp_s(x) Index(Children(x),3)
#define Indexed_func_declHas_func_name(x) Index(Children(x),1)
#define Int_32_rangeHas_direction(x) Index(Children(x),1)
#define Int_32_rangeHas_low_bound(x) Index(Children(x),2)
#define Int_32_rangeHas_high_bound(x) Index(Children(x),3)
#define Int_32_valueHas_int_32(x) Index(Children(x),1)
#define Int_64_valueHas_int_64(x) Index(Children(x),1)
#define Integer_type_declHas_evaluation_time(x) Index(Children(x),1)
#define Integer_type_declHas_constraint(x) Index(Children(x),2)
#define Integer_type_declHas_id(x) Index(Children(x),3)
#define Integer_type_declHas_enclosing_scope(x) Index(Children(x),4)
#define Integer_type_declHas_srcpos(x) Index(Children(x),5)
#define Integer_type_declHas_user_att_s(x) Index(Children(x),6)
#define Label_declHas_srcpos(x) Index(Children(x),1)
#define Label_declHas_enclosing_scope(x) Index(Children(x),2)
#define Label_declHas_id(x) Index(Children(x),3)
#define Label_declHas_labeled_stm(x) Index(Children(x),4)
#define Label_declHas_user_att_s(x) Index(Children(x),5)
#define Loop_stmHas_srcpos(x) Index(Children(x),1)
#define Loop_stmHas_label(x) Index(Children(x),2)
#define Loop_stmHas_scheme(x) Index(Children(x),3)
#define Loop_stmHas_end_srcpos(x) Index(Children(x),4)
#define Loop_stmHas_stm_s(x) Index(Children(x),5)
#define Loop_stmHas_enclosing_scope(x) Index(Children(x),6)
#define Named_agg_assocHas_associated_exp(x) Index(Children(x),1)
#define Named_agg_assocIs_associated_up_to(x) Index(Children(x),2)
#define Named_array_aggHas_evaluation_time(x) Index(Children(x),1)
#define Named_array_aggHas_constraint(x) Index(Children(x),2)
#define Named_array_aggHas_assoc_s(x) Index(Children(x),3)
#define Named_array_aggHas_srcpos(x) Index(Children(x),4)
#define Named_array_aggHas_dimension(x) Index(Children(x),5)
#define Named_sub_aggHas_evaluation_time(x) Index(Children(x),1)
#define Named_sub_aggHas_assoc_s(x) Index(Children(x),2)
#define Named_sub_aggHas_dimension(x) Index(Children(x),3)
#define Named_sub_aggHas_srcpos(x) Index(Children(x),4)
#define Next_stmHas_srcpos(x) Index(Children(x),1)
#define Next_stmHas_condition(x) Index(Children(x),2)
#define Next_stmHas_loop_stm(x) Index(Children(x),3)
#define Next_stmHas_label(x) Index(Children(x),4)
#define Next_stmHas_enclosing_scope(x) Index(Children(x),5)
#define Non_constraintHas_evaluation_time(x) Index(Children(x),1)
#define Non_constraintIn_enclosing_decl(x) Index(Children(x),2)
#define Non_constraintIs_type(x) Index(Children(x),3)
#define Non_constraintIs_subtype(x) Index(Children(x),4)
#define Non_static_array_aggHas_evaluation_time(x) Index(Children(x),1)
#define Non_static_array_aggHas_constraint(x) Index(Children(x),2)
#define Non_static_array_aggHas_associated_exp(x) Index(Children(x),3)
#define Non_static_array_aggIs_associated_to(x) Index(Children(x),4)
#define Non_static_array_aggHas_dimension(x) Index(Children(x),5)
#define Non_static_array_aggHas_srcpos(x) Index(Children(x),6)
#define Non_static_sub_aggHas_evaluation_time(x) Index(Children(x),1)
#define Non_static_sub_aggHas_associated_exp(x) Index(Children(x),2)
#define Non_static_sub_aggIs_associated_to(x) Index(Children(x),3)
#define Non_static_sub_aggHas_dimension(x) Index(Children(x),4)
#define Non_static_sub_aggHas_srcpos(x) Index(Children(x),5)
#define Null_array_aggHas_evaluation_time(x) Index(Children(x),1)
#define Null_array_aggHas_constraint(x) Index(Children(x),2)
#define Null_array_aggHas_associated_exp(x) Index(Children(x),3)
#define Null_array_aggIs_associated_to(x) Index(Children(x),4)
#define Null_array_aggHas_dimension(x) Index(Children(x),5)
#define Null_array_aggHas_srcpos(x) Index(Children(x),6)
#define Null_literalHas_evaluation_time(x) Index(Children(x),1)
#define Null_literalHas_constraint(x) Index(Children(x),2)
#define Null_literalHas_srcpos(x) Index(Children(x),3)
#define Null_stmHas_srcpos(x) Index(Children(x),1)
#define Null_stmHas_label(x) Index(Children(x),2)
#define Null_stmHas_enclosing_scope(x) Index(Children(x),3)
#define Null_sub_aggHas_evaluation_time(x) Index(Children(x),1)
#define Null_sub_aggHas_associated_exp(x) Index(Children(x),2)
#define Null_sub_aggIs_associated_to(x) Index(Children(x),3)
#define Null_sub_aggHas_dimension(x) Index(Children(x),4)
#define Null_sub_aggHas_srcpos(x) Index(Children(x),5)
#define Null_waveform_elementHas_time_exp(x) Index(Children(x),1)
#define Numeric_valueHas_evaluation_time(x) Index(Children(x),1)
#define Numeric_valueHas_constraint(x) Index(Children(x),2)
#define Numeric_valueHas_srcpos(x) Index(Children(x),3)
#define Numeric_valueHas_value(x) Index(Children(x),4)
#define Operator_declHas_evaluation_time(x) Index(Children(x),1)
#define Operator_declHas_constraint(x) Index(Children(x),2)
#define Operator_declHas_id(x) Index(Children(x),3)
#define Operator_declHas_enclosing_scope(x) Index(Children(x),4)
#define Operator_declHas_srcpos(x) Index(Children(x),5)
#define Operator_declHas_operator(x) Index(Children(x),6)
#define Operator_declHas_param_s(x) Index(Children(x),7)
#define Operator_declHas_body_decl(x) Index(Children(x),8)
#define Operator_declHas_user_att_s(x) Index(Children(x),9)
#define Operator_declHas_pureness(x) Index(Children(x),10)
#define Others_agg_assocHas_associated_exp(x) Index(Children(x),1)
#define Others_case_alternativeHas_stm_s(x) Index(Children(x),1)
#define Others_selected_waveform_altHas_waveform_s(x) Index(Children(x),1)
#define Package_bodyHas_srcpos(x) Index(Children(x),1)
#define Package_bodyHas_name(x) Index(Children(x),2)
#define Package_bodyHas_id(x) Index(Children(x),3)
#define Package_bodyHas_end_srcpos(x) Index(Children(x),4)
#define Package_bodyHas_decl_s(x) Index(Children(x),5)
#define Package_bodyHas_implicit_decl_s(x) Index(Children(x),6)
#define Package_bodyHas_enclosing_scope(x) Index(Children(x),7)
#define Package_declHas_srcpos(x) Index(Children(x),1)
#define Package_declHas_enclosing_scope(x) Index(Children(x),2)
#define Package_declHas_id(x) Index(Children(x),3)
#define Package_declHas_end_srcpos(x) Index(Children(x),4)
#define Package_declHas_decl_s(x) Index(Children(x),5)
#define Package_declHas_implicit_decl_s(x) Index(Children(x),6)
#define Package_declHas_user_att_s(x) Index(Children(x),7)
#define Package_declHas_deferred_constant_s(x) Index(Children(x),8)
#define Package_declHas_type_decl_s(x) Index(Children(x),9)
#define Package_declHas_use_clause_s(x) Index(Children(x),10)
#define Package_declHas_subprogram_decl_s(x) Index(Children(x),11)
#define Partial_association_of_formalHas_actual(x) Index(Children(x),1)
#define Partial_association_of_formalHas_formal_subelement(x) Index(Children(x),2)
#define Phy_unit_declHas_evaluation_time(x) Index(Children(x),1)
#define Phy_unit_declHas_constraint(x) Index(Children(x),2)
#define Phy_unit_declHas_id(x) Index(Children(x),3)
#define Phy_unit_declHas_enclosing_scope(x) Index(Children(x),4)
#define Phy_unit_declHas_srcpos(x) Index(Children(x),5)
#define Phy_unit_declHas_value(x) Index(Children(x),6)
#define Phy_unit_declHas_user_att_s(x) Index(Children(x),7)
#define Physical_type_declHas_evaluation_time(x) Index(Children(x),1)
#define Physical_type_declHas_constraint(x) Index(Children(x),2)
#define Physical_type_declHas_id(x) Index(Children(x),3)
#define Physical_type_declHas_end_srcpos(x) Index(Children(x),4)
#define Physical_type_declHas_base(x) Index(Children(x),5)
#define Physical_type_declHas_enclosing_scope(x) Index(Children(x),6)
#define Physical_type_declHas_srcpos(x) Index(Children(x),7)
#define Physical_type_declHas_secondary_s(x) Index(Children(x),8)
#define Physical_type_declHas_user_att_s(x) Index(Children(x),9)
#define Physical_valueHas_value(x) Index(Children(x),1)
#define Physical_valueHas_base(x) Index(Children(x),2)
#define Port_declHas_evaluation_time(x) Index(Children(x),1)
#define Port_declHas_constraint(x) Index(Children(x),2)
#define Port_declHas_id(x) Index(Children(x),3)
#define Port_declHas_class(x) Index(Children(x),4)
#define Port_declHas_default(x) Index(Children(x),5)
#define Port_declHas_disconnect_specs(x) Index(Children(x),6)
#define Port_declHas_enclosing_scope(x) Index(Children(x),7)
#define Port_declHas_srcpos(x) Index(Children(x),8)
#define Port_declHas_guarded_kind(x) Index(Children(x),9)
#define Port_declHas_mode(x) Index(Children(x),10)
#define Port_declHas_resolution(x) Index(Children(x),11)
#define Port_declHas_user_att_s(x) Index(Children(x),12)
#define Positional_agg_assocHas_associated_exp(x) Index(Children(x),1)
#define Positional_array_aggHas_evaluation_time(x) Index(Children(x),1)
#define Positional_array_aggHas_constraint(x) Index(Children(x),2)
#define Positional_array_aggHas_assoc_s(x) Index(Children(x),3)
#define Positional_array_aggHas_dimension(x) Index(Children(x),4)
#define Positional_array_aggHas_srcpos(x) Index(Children(x),5)
#define Positional_sub_aggHas_evaluation_time(x) Index(Children(x),1)
#define Positional_sub_aggHas_assoc_s(x) Index(Children(x),2)
#define Positional_sub_aggHas_dimension(x) Index(Children(x),3)
#define Positional_sub_aggHas_srcpos(x) Index(Children(x),4)
#define Pre_defined_att_declHas_evaluation_time(x) Index(Children(x),1)
#define Pre_defined_att_declHas_enclosing_scope(x) Index(Children(x),2)
#define Pre_defined_att_declHas_id(x) Index(Children(x),3)
#define Pre_defined_att_declHas_attribute_number(x) Index(Children(x),4)
#define Proc_bodyHas_srcpos(x) Index(Children(x),1)
#define Proc_bodyHas_decl_s(x) Index(Children(x),2)
#define Proc_bodyHas_implicit_decl_s(x) Index(Children(x),3)
#define Proc_bodyHas_end_srcpos(x) Index(Children(x),4)
#define Proc_bodyHas_enclosing_scope(x) Index(Children(x),5)
#define Proc_bodyHas_name(x) Index(Children(x),6)
#define Proc_bodyHas_stm_s(x) Index(Children(x),7)
#define Proc_call_stmHas_srcpos(x) Index(Children(x),1)
#define Proc_call_stmHas_assoc_s(x) Index(Children(x),2)
#define Proc_call_stmHas_proc_name(x) Index(Children(x),3)
#define Proc_call_stmHas_label(x) Index(Children(x),4)
#define Proc_call_stmHas_enclosing_scope(x) Index(Children(x),5)
#define Proc_declHas_evaluation_time(x) Index(Children(x),1)
#define Proc_declHas_enclosing_scope(x) Index(Children(x),2)
#define Proc_declHas_id(x) Index(Children(x),3)
#define Proc_declHas_srcpos(x) Index(Children(x),4)
#define Proc_declHas_param_s(x) Index(Children(x),5)
#define Proc_declHas_body_decl(x) Index(Children(x),6)
#define Proc_declHas_user_att_s(x) Index(Children(x),7)
#define Process_stmHas_srcpos(x) Index(Children(x),1)
#define Process_stmHas_decl_s(x) Index(Children(x),2)
#define Process_stmHas_implicit_decl_s(x) Index(Children(x),3)
#define Process_stmHas_end_srcpos(x) Index(Children(x),4)
#define Process_stmHas_sensitivity_s(x) Index(Children(x),5)
#define Process_stmHas_label(x) Index(Children(x),6)
#define Process_stmHas_stm_s(x) Index(Children(x),7)
#define Process_stmHas_enclosing_scope(x) Index(Children(x),8)
#define Process_stmHas_postponed(x) Index(Children(x),9)
#define QualifiedHas_evaluation_time(x) Index(Children(x),1)
#define QualifiedHas_constraint(x) Index(Children(x),2)
#define QualifiedHas_srcpos(x) Index(Children(x),3)
#define QualifiedHas_qualified_exp(x) Index(Children(x),4)
#define QualifiedHas_value(x) Index(Children(x),5)
#define Range_attribute_constraintHas_evaluation_time(x) Index(Children(x),1)
#define Range_attribute_constraintHas_constraint(x) Index(Children(x),2)
#define Range_attribute_constraintIs_type(x) Index(Children(x),3)
#define Range_attribute_constraintIs_subtype(x) Index(Children(x),4)
#define Range_attribute_constraintIn_enclosing_decl(x) Index(Children(x),5)
#define Range_attribute_constraintHas_direction(x) Index(Children(x),6)
#define Range_attribute_constraintHas_index(x) Index(Children(x),7)
#define Range_attribute_constraintHas_left_bound(x) Index(Children(x),8)
#define Range_attribute_constraintHas_null_range_indicator(x) Index(Children(x),9)
#define Range_attribute_constraintHas_attribute_prefix(x) Index(Children(x),10)
#define Range_attribute_constraintHas_right_bound(x) Index(Children(x),11)
#define Real_valueHas_real(x) Index(Children(x),1)
#define Record_aggHas_evaluation_time(x) Index(Children(x),1)
#define Record_aggHas_constraint(x) Index(Children(x),2)
#define Record_aggHas_assoc_s(x) Index(Children(x),3)
#define Record_aggHas_srcpos(x) Index(Children(x),4)
#define Record_type_declHas_evaluation_time(x) Index(Children(x),1)
#define Record_type_declHas_constraint(x) Index(Children(x),2)
#define Record_type_declHas_id(x) Index(Children(x),3)
#define Record_type_declHas_end_srcpos(x) Index(Children(x),4)
#define Record_type_declHas_element_s(x) Index(Children(x),5)
#define Record_type_declHas_enclosing_scope(x) Index(Children(x),6)
#define Record_type_declHas_srcpos(x) Index(Children(x),7)
#define Record_type_declHas_access_subelement(x) Index(Children(x),8)
#define Record_type_declHas_user_att_s(x) Index(Children(x),9)
#define Report_stmHas_srcpos(x) Index(Children(x),1)
#define Report_stmHas_report_exp(x) Index(Children(x),2)
#define Report_stmHas_severity_exp(x) Index(Children(x),3)
#define Report_stmHas_label(x) Index(Children(x),4)
#define Report_stmHas_enclosing_scope(x) Index(Children(x),5)
#define Resolvable_subtype_declHas_evaluation_time(x) Index(Children(x),1)
#define Resolvable_subtype_declHas_constraint(x) Index(Children(x),2)
#define Resolvable_subtype_declHas_id(x) Index(Children(x),3)
#define Resolvable_subtype_declHas_enclosing_scope(x) Index(Children(x),4)
#define Resolvable_subtype_declHas_srcpos(x) Index(Children(x),5)
#define Resolvable_subtype_declHas_resolve_func(x) Index(Children(x),6)
#define Resolvable_subtype_declHas_user_att_s(x) Index(Children(x),7)
#define Return_stmHas_srcpos(x) Index(Children(x),1)
#define Return_stmHas_return_exp(x) Index(Children(x),2)
#define Return_stmHas_label(x) Index(Children(x),3)
#define Return_stmHas_enclosing_scope(x) Index(Children(x),4)
#define Reverse_range_attribute_constraintHas_evaluation_time(x) Index(Children(x),1)
#define Reverse_range_attribute_constraintHas_constraint(x) Index(Children(x),2)
#define Reverse_range_attribute_constraintIs_type(x) Index(Children(x),3)
#define Reverse_range_attribute_constraintIs_subtype(x) Index(Children(x),4)
#define Reverse_range_attribute_constraintIn_enclosing_decl(x) Index(Children(x),5)
#define Reverse_range_attribute_constraintHas_direction(x) Index(Children(x),6)
#define Reverse_range_attribute_constraintHas_index(x) Index(Children(x),7)
#define Reverse_range_attribute_constraintHas_left_bound(x) Index(Children(x),8)
#define Reverse_range_attribute_constraintHas_null_range_indicator(x) Index(Children(x),9)
#define Reverse_range_attribute_constraintHas_attribute_prefix(x) Index(Children(x),10)
#define Reverse_range_attribute_constraintHas_right_bound(x) Index(Children(x),11)
#define Selected_elementHas_evaluation_time(x) Index(Children(x),1)
#define Selected_elementHas_constraint(x) Index(Children(x),2)
#define Selected_elementHas_base_obj_def(x) Index(Children(x),3)
#define Selected_elementHas_srcpos(x) Index(Children(x),4)
#define Selected_elementHas_prefix(x) Index(Children(x),5)
#define Selected_elementHas_suffix(x) Index(Children(x),6)
#define Selected_signal_assign_stmHas_srcpos(x) Index(Children(x),1)
#define Selected_signal_assign_stmHas_signal_name(x) Index(Children(x),2)
#define Selected_signal_assign_stmHas_transport(x) Index(Children(x),3)
#define Selected_signal_assign_stmHas_guard(x) Index(Children(x),4)
#define Selected_signal_assign_stmHas_select_exp(x) Index(Children(x),5)
#define Selected_signal_assign_stmHas_selected_waveform_s(x) Index(Children(x),6)
#define Selected_signal_assign_stmHas_label(x) Index(Children(x),7)
#define Selected_signal_assign_stmHas_postponed(x) Index(Children(x),8)
#define Selected_signal_assign_stmHas_reject_time(x) Index(Children(x),9)
#define Selected_signal_assign_stmHas_enclosing_scope(x) Index(Children(x),10)
#define Selected_waveform_alt_for_discreteIs_associated_up_to(x) Index(Children(x),1)
#define Selected_waveform_alt_for_discreteHas_waveform_s(x) Index(Children(x),2)
#define Selected_waveform_alt_for_discreteHas_same_waveform(x) Index(Children(x),3)
#define Selected_waveform_alt_for_stringIs_associated_to_str(x) Index(Children(x),1)
#define Selected_waveform_alt_for_stringHas_waveform_s(x) Index(Children(x),2)
#define Selected_waveform_alt_for_stringHas_same_waveform(x) Index(Children(x),3)
#define Shared_variable_declHas_evaluation_time(x) Index(Children(x),1)
#define Shared_variable_declHas_constraint(x) Index(Children(x),2)
#define Shared_variable_declHas_id(x) Index(Children(x),3)
#define Shared_variable_declHas_enclosing_scope(x) Index(Children(x),4)
#define Shared_variable_declHas_srcpos(x) Index(Children(x),5)
#define Shared_variable_declHas_user_att_s(x) Index(Children(x),6)
#define Shared_variable_declHas_value_exp(x) Index(Children(x),7)
#define Signal_assign_stmHas_srcpos(x) Index(Children(x),1)
#define Signal_assign_stmHas_signal_name(x) Index(Children(x),2)
#define Signal_assign_stmHas_transport(x) Index(Children(x),3)
#define Signal_assign_stmHas_waveform_s(x) Index(Children(x),4)
#define Signal_assign_stmHas_label(x) Index(Children(x),5)
#define Signal_assign_stmHas_reject_time(x) Index(Children(x),6)
#define Signal_assign_stmHas_enclosing_scope(x) Index(Children(x),7)
#define Signal_declHas_evaluation_time(x) Index(Children(x),1)
#define Signal_declHas_constraint(x) Index(Children(x),2)
#define Signal_declHas_id(x) Index(Children(x),3)
#define Signal_declHas_disconnect_specs(x) Index(Children(x),4)
#define Signal_declHas_enclosing_scope(x) Index(Children(x),5)
#define Signal_declHas_srcpos(x) Index(Children(x),6)
#define Signal_declHas_guarded_kind(x) Index(Children(x),7)
#define Signal_declHas_resolution(x) Index(Children(x),8)
#define Signal_declHas_user_att_s(x) Index(Children(x),9)
#define Signal_declHas_value_exp(x) Index(Children(x),10)
#define Signal_disconnect_specHas_disconnection_spec(x) Index(Children(x),1)
#define Signal_spec_aggHas_spec_s(x) Index(Children(x),1)
#define Signal_spec_assocHas_associated_spec(x) Index(Children(x),1)
#define Signal_spec_assocIs_associated_to(x) Index(Children(x),2)
#define Simple_attribute_refHas_evaluation_time(x) Index(Children(x),1)
#define Simple_attribute_refHas_constraint(x) Index(Children(x),2)
#define Simple_attribute_refHas_attribute(x) Index(Children(x),3)
#define Simple_attribute_refHas_srcpos(x) Index(Children(x),4)
#define Simple_attribute_refHas_attribute_prefix(x) Index(Children(x),5)
#define Simple_attribute_refHas_value(x) Index(Children(x),6)
#define SliceHas_evaluation_time(x) Index(Children(x),1)
#define SliceHas_constraint(x) Index(Children(x),2)
#define SliceHas_base_obj_def(x) Index(Children(x),3)
#define SliceHas_srcpos(x) Index(Children(x),4)
#define SliceHas_index_range(x) Index(Children(x),5)
#define SliceHas_prefix(x) Index(Children(x),6)
#define String_literalHas_evaluation_time(x) Index(Children(x),1)
#define String_literalHas_constraint(x) Index(Children(x),2)
#define String_literalHas_dimension(x) Index(Children(x),3)
#define String_literalHas_srcpos(x) Index(Children(x),4)
#define String_literalHas_value(x) Index(Children(x),5)
#define String_literal_sub_aggHas_evaluation_time(x) Index(Children(x),1)
#define String_literal_sub_aggHas_dimension(x) Index(Children(x),2)
#define String_literal_sub_aggHas_srcpos(x) Index(Children(x),3)
#define String_literal_sub_aggHas_value(x) Index(Children(x),4)
#define String_valueHas_str_rep(x) Index(Children(x),1)
#define Subp_param_declHas_evaluation_time(x) Index(Children(x),1)
#define Subp_param_declHas_constraint(x) Index(Children(x),2)
#define Subp_param_declHas_id(x) Index(Children(x),3)
#define Subp_param_declHas_class(x) Index(Children(x),4)
#define Subp_param_declHas_default(x) Index(Children(x),5)
#define Subp_param_declHas_enclosing_scope(x) Index(Children(x),6)
#define Subp_param_declHas_srcpos(x) Index(Children(x),7)
#define Subp_param_declHas_guarded_kind(x) Index(Children(x),8)
#define Subp_param_declHas_mode(x) Index(Children(x),9)
#define Subp_param_declHas_spec_param_decl(x) Index(Children(x),10)
#define Subp_param_declHas_user_att_s(x) Index(Children(x),11)
#define Subtype_indicatorHas_resolve_func(x) Index(Children(x),1)
#define Subtype_indicatorHas_constraint(x) Index(Children(x),2)
#define Symbol_entry_in_tableHas_def_s(x) Index(Children(x),1)
#define Symbol_entry_in_tableHas_next_st_element(x) Index(Children(x),2)
#define Symbol_entry_in_tableHas_h_value(x) Index(Children(x),3)
#define Symbol_entry_in_tableHas_def(x) Index(Children(x),4)
#define Symbol_entry_in_tableHas_profile_s(x) Index(Children(x),5)
#define Symbol_entry_in_tableHas_name_prefix(x) Index(Children(x),6)
#define Symbol_entry_in_tableHas_simple_name(x) Index(Children(x),7)
#define Type_conversionHas_evaluation_time(x) Index(Children(x),1)
#define Type_conversionHas_constraint(x) Index(Children(x),2)
#define Type_conversionHas_converted_exp(x) Index(Children(x),3)
#define Type_conversionHas_srcpos(x) Index(Children(x),4)
#define Type_conversionHas_value(x) Index(Children(x),5)
#define Type_conversion_on_assocHas_converted_exp(x) Index(Children(x),1)
#define Type_conversion_on_assocHas_constraint(x) Index(Children(x),2)
#define Type_conversion_on_partial_formalHas_converted_subelement(x) Index(Children(x),1)
#define Type_conversion_on_partial_formalHas_constraint(x) Index(Children(x),2)
#define Unary_operationHas_evaluation_time(x) Index(Children(x),1)
#define Unary_operationHas_constraint(x) Index(Children(x),2)
#define Unary_operationHas_srcpos(x) Index(Children(x),3)
#define Unary_operationHas_value(x) Index(Children(x),4)
#define Unary_operationHas_right_exp(x) Index(Children(x),5)
#define Unary_operationHas_func_name(x) Index(Children(x),6)
#define UnconnectedHas_srcpos(x) Index(Children(x),1)
#define Unconstrained_array_type_declHas_evaluation_time(x) Index(Children(x),1)
#define Unconstrained_array_type_declHas_constraint(x) Index(Children(x),2)
#define Unconstrained_array_type_declHas_id(x) Index(Children(x),3)
#define Unconstrained_array_type_declHas_dimension(x) Index(Children(x),4)
#define Unconstrained_array_type_declHas_elem_subtype(x) Index(Children(x),5)
#define Unconstrained_array_type_declHas_enclosing_scope(x) Index(Children(x),6)
#define Unconstrained_array_type_declHas_srcpos(x) Index(Children(x),7)
#define Unconstrained_array_type_declHas_access_subelement(x) Index(Children(x),8)
#define Unconstrained_array_type_declHas_index_range_s(x) Index(Children(x),9)
#define Unconstrained_array_type_declHas_user_att_s(x) Index(Children(x),10)
#define Univ_integer_type_declHas_enclosing_scope(x) Index(Children(x),1)
#define Univ_integer_type_declHas_constraint(x) Index(Children(x),2)
#define Univ_integer_type_declHas_id(x) Index(Children(x),3)
#define Univ_real_type_declHas_enclosing_scope(x) Index(Children(x),1)
#define Univ_real_type_declHas_constraint(x) Index(Children(x),2)
#define Univ_real_type_declHas_id(x) Index(Children(x),3)
#define Use_clauseHas_name(x) Index(Children(x),1)
#define Use_clauseHas_library(x) Index(Children(x),2)
#define Variable_assign_stmHas_srcpos(x) Index(Children(x),1)
#define Variable_assign_stmHas_assigned_exp(x) Index(Children(x),2)
#define Variable_assign_stmHas_variable_name(x) Index(Children(x),3)
#define Variable_assign_stmHas_label(x) Index(Children(x),4)
#define Variable_assign_stmHas_enclosing_scope(x) Index(Children(x),5)
#define Variable_declHas_evaluation_time(x) Index(Children(x),1)
#define Variable_declHas_constraint(x) Index(Children(x),2)
#define Variable_declHas_id(x) Index(Children(x),3)
#define Variable_declHas_enclosing_scope(x) Index(Children(x),4)
#define Variable_declHas_srcpos(x) Index(Children(x),5)
#define Variable_declHas_user_att_s(x) Index(Children(x),6)
#define Variable_declHas_value_exp(x) Index(Children(x),7)
#define Wait_stmHas_srcpos(x) Index(Children(x),1)
#define Wait_stmHas_condition(x) Index(Children(x),2)
#define Wait_stmHas_sensitive_s(x) Index(Children(x),3)
#define Wait_stmHas_time_limit(x) Index(Children(x),4)
#define Wait_stmHas_label(x) Index(Children(x),5)
#define Wait_stmHas_enclosing_scope(x) Index(Children(x),6)
#define Waveform_elementHas_time_exp(x) Index(Children(x),1)
#define Waveform_elementHas_waveform_value_exp(x) Index(Children(x),2)
#define While_iterationHas_condition(x) Index(Children(x),1)


extern Table *VIF_InitTable();

#endif

