/* $Id: finder.c,v 34.2 1995/03/29 13:03:58 ella Exp $. */


/* 
    ************************************************************************
    This Program is the property of the Secretary of State for Defence
    (United Kingdom) acting through the Defence Research Agency (DRA). Use,
    reproduction, production of amended versions and/or transfer of this
    Program is permitted provided that:

  (a)  this legend be preserved on any such reproduction and amended version,
  (b)  any amended version of this Program be clearly marked to show the
       nature of the amendment and of the name of the amending organisation,
  and
  (c)  any recipient  of such reproduction or amended version accept the
       conditions set out in this legend.

                         Crown Copyright, (c)   1993

                             All rights reserved.

    The Secretary of State for Defence (United Kingdom) acting through his
    Defence Research Agency (DRA) gives no warranty that any element of the
    Software is suitable for any purpose and he shall not be liable for any
    loss or damage including loss or damage resulting in injury or death
    howsoever caused which results from the use of the Software, or any
    developments adaptions modifications translations and enhancements
    thereof.

    The original authors may be contacted via email on ella@dra.hmg.gb or by
    writing to ELLA Office, DRA, St Andrews Road, Malvern, Worcs WR14 3PS, UK.
    ************************************************************************

   ------------------------- Change History ---------------------------
30:08:94  33.001  ELLA  NewConFig Install in new configuration management
                                  system old version was 1.6 
29:03:95  34.002  ELLA  Modcprght Change copyright header
??:??:??   ?.???  ????
*/

/*
  Generated by: $Id: finder.c,v 34.2 1995/03/29 13:03:58 ella Exp $.
  Time of generation: Tue Jan 21 19:08:37 GMT 1992
.
*/

#include "alien.h"

ACI_EVAL_FN last_finder(){}	/* never called */

/* the extern definitions for the finders */

extern ACI_EVAL_FN
  finder(),
  typecheatFinder(),
  compareFinder(),
  last_finder();

/* the finder table */

ACI_EVAL_FN (*(finders[]))() = {
  finder,
  typecheatFinder,
  compareFinder,
  last_finder
};

/*  THE FINDER */

ACI_EVAL_FN built_in_finder(name,upb_name,inputs,upb_inputs,output,macparams,upb_macparams,workspace,history,decl_id)
char *name;
unsigned upb_name;
unsigned *inputs;
unsigned upb_inputs;
unsigned output;
int *macparams;
unsigned upb_macparams;
unsigned *workspace;
unsigned *history;
unsigned *decl_id;
{
    ACI_EVAL_FN (**this_finder)(), this_eval_fn;

    /* call all known finders until one succeeds */

    for( this_finder = &finders[0]; *this_finder != last_finder; this_finder++)
	if( (this_eval_fn = (**this_finder)(name,upb_name,inputs,upb_inputs,output,macparams,upb_macparams,workspace,history,decl_id)) != 0 )
	    return this_eval_fn;

    /* failed if we get here */

    return 0;
}
